#ifndef _ENUMS_H_
#define _ENUMS_H_

enum ComponentIds
{
    COMPONENT_TRANSFORM = 0,
    COMPONENT_MOVEMENT,
    COMPONENT_PLATFORMER_PHYSICS,
    COMPONENT_PLATFORMER_CONTROLLER,
    COMPONENT_ANIMATION,
    COMPONENT_TEXTURE
};

enum GameObjectTypes
{
    GAMEOBJECT_PLAYER = 0,
    GAMEOBJECT_ENEMY
};

enum Key
{
	KEY_PRESSED_UP = 0,
	KEY_PRESSED_DOWN,
	KEY_PRESSED_LEFT,
	KEY_PRESSED_RIGHT,
    KEY_PRESSED_SPACE,
	KEY_RELEASED_LEFT,
    KEY_RELEASED_RIGHT,
    KEY_RELEASED_UP,
    KEY_RELEASED_DOWN,
    KEY_RELEASED_SPACE,
    KEY_NONE
};

enum Textures
{
    TEXTURE_PLAYER = 0
};

enum Animations
{
    ANIMATION_STAND_LEFT = 0,
    ANIMATION_STAND_RIGHT,
    ANIMATION_WALK_LEFT,
    ANIMATION_WALK_RIGHT,
    ANIMATION_JUMP_LEFT,
    ANIMATION_JUMP_RIGHT
};

#endif